document.write('<head>');
document.write('    <meta charset="UTF-8">');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('    <title>Expanding Dropdown Menu In JavaScript Example</title>');
document.write('    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300,400,500,700&display=swap" rel="stylesheet">');
document.write('    <link rel="stylesheet" href="https://www.cssscript.com/demo/sticky.css">');
document.write('    <link rel="stylesheet" href="style.css">');
document.write('    <style>');
document.write('  ');
document.write('  @import url("https://fonts.googleapis.com/css2?family=Ubuntu:wght@300,400,500,700&display=swap");');
document.write('  ');
document.write('  * {');
document.write('  margin: 0;');
document.write('  padding: 0;');
document.write('  box-sizing: border-box;');
document.write('  font-family: "Ubuntu", sans-serif;');
document.write('  }');
document.write('  ');
document.write('  ');
document.write('  .navigation {');
document.write('  position: fixed;');
document.write('  top: 20px;');
document.write('  right: 20px;');
document.write('  width: 120px;');
document.write('  height: 60px;');
document.write('  background: #fff;');
document.write('  box-shadow: 0 25px 35px rgba(0, 0, 0, 0.1);');
document.write('  display: flex;');
document.write('  justify-content: space-between;');
document.write('  transition: height 0.5s, width 0.5s;');
document.write('  transition-delay: 0s, 0.75s;');
document.write('  overflow: hidden;');
document.write('  }');
document.write('  ');
document.write('  .navigation.active {');
document.write('  width: 300px;');
document.write('  height: 350px;');
document.write('  transition: width 0.5s, height 0.5s;');
document.write('  transition-delay: 0s, 0.75s;');
document.write('  }');
document.write('  ');
document.write('  .navigation .userBx {');
document.write('  position: relative;');
document.write('  width: 60px;');
document.write('  height: 60px;');
document.write('  background: #fff;');
document.write('  display: flex;');
document.write('  align-items: center;');
document.write('  overflow: hidden;');
document.write('  transition: 0.5s;');
document.write('  transition-delay: 0.5s;');
document.write('  }');
document.write('  ');
document.write('  .navigation.active .userBx {');
document.write('  width: calc(100% - 60px);');
document.write('  transition-delay: 0s;');
document.write('  }');
document.write('  ');
document.write('  .navigation .userBx .username {');
document.write('  white-space: nowrap;');
document.write('  color: #555;');
document.write('  font-size: 1.1em;');
document.write('  }');
document.write('  ');
document.write('  .navigation .userBx .imgBx {');
document.write('  position: relative;');
document.write('  min-width: 60px;');
document.write('  height: 60px;');
document.write('  overflow: hidden;');
document.write('  background: #000;');
document.write('  border-radius: 50%;');
document.write('  border: 10px solid #fff;');
document.write('  }');
document.write('  ');
document.write('  .navigation .userBx .imgBx img {');
document.write('  position: absolute;');
document.write('  top: 0;');
document.write('  left: 0;');
document.write('  width: 100%;');
document.write('  height: 100%;');
document.write('  object-fit: cover;');
document.write('  }');
document.write('  ');
document.write('  /* Hamburguer toggle menu */');
document.write('  ');
document.write('  .navigation .menuToggle {');
document.write('  position: relative;');
document.write('  width: 60px;');
document.write('  height: 60px;');
document.write('  background: #fff;');
document.write('  cursor: pointer;');
document.write('  display: flex;');
document.write('  justify-content: center;');
document.write('  align-items: center;');
document.write('  }');
document.write('  ');
document.write('  .navigation .menuToggle::before {');
document.write('  content: "";');
document.write('  position: absolute;');
document.write('  width: 32px;');
document.write('  height: 2px;');
document.write('  background: #555;');
document.write('  transform: translateY(-10px);');
document.write('  box-shadow: 0 10px #555;');
document.write('  transition: 0.5s;');
document.write('  }');
document.write('  ');
document.write('  .navigation .menuToggle::after {');
document.write('  content: "";');
document.write('  position: absolute;');
document.write('  width: 32px;');
document.write('  height: 2px;');
document.write('  background: #555;');
document.write('  transform: translateY(10px);');
document.write('  transition: 0.5s;');
document.write('  }');
document.write('  ');
document.write('  .navigation.active .menuToggle::before {');
document.write('  transform: translateY(0px) rotate(45deg);');
document.write('  box-shadow: 0 0 #555;');
document.write('  }');
document.write('  ');
document.write('  .navigation.active .menuToggle::after {');
document.write('  transform: translateY(0px) rotate(-45deg);');
document.write('  }');
document.write('  ');
document.write('  .menu {');
document.write('  position: absolute;');
document.write('  width: 100%;');
document.write('  height: calc(100% - 60px);');
document.write('  margin-top: 60px;');
document.write('  padding: 20px;');
document.write('  border-top: 1px solid rgba(0, 0, 0, 0.1);');
document.write('  }');
document.write('  ');
document.write('  .menu li {');
document.write('  list-style: none;');
document.write('  }');
document.write('  ');
document.write('  .menu li a {');
document.write('  display: flex;');
document.write('  align-items: center;');
document.write('  gap: 10px;');
document.write('  margin: 20px 0;');
document.write('  font-size: 1em;');
document.write('  text-decoration: none;');
document.write('  color: #555;');
document.write('  }');
document.write('  ');
document.write('  .menu li a:hover {');
document.write('  color: #4e65ff;');
document.write('  }');
document.write('  ');
document.write('  .menu li a ion-icon {');
document.write('  font-size: 1.5em;');
document.write('  }');
document.write('    </style>');
document.write('    <script>');
document.write('  <!DOCTYPE html>');
document.write('  <html lang="pt-br">');
document.write('  <head>');
document.write('    <meta charset="UTF-8" />');
document.write('    <meta http-equiv="X-UA-Compatible" content="IE=edge" />');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0" />');
document.write('    <title>Expanding Dropdown Menu In JavaScript Example</title>');
document.write('    <link href="https://www.cssscript.com/demo/sticky.css" rel="stylesheet" type="text/css">');
document.write('    <link rel="stylesheet" href="style.css" />');
document.write('    <style>');
document.write('      .container { margin: 150px auto; max-width: 960px; }');
document.write('    </style>');
document.write('  </head>');
document.write('  <body>');
document.write('    <div class="container">');
document.write('    <h1>Expanding Dropdown Menu In JavaScript Example</h1>');
document.write('    <div style="margin:2rem auto"><div id="carbon-block"></div>');
document.write('    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2783044520727903"');
document.write('     crossorigin="anonymous"></script>');
document.write('  <!-- CSSScript Demo Page -->');
document.write('  <ins class="adsbygoogle"');
document.write('     style="display:inline-block;width:728px;height:90px"');
document.write('     data-ad-client="ca-pub-2783044520727903"');
document.write('     data-ad-slot="3025259193"></ins>');
document.write('  <script>');
document.write('     (adsbygoogle = window.adsbygoogle || []).push({});');
document.write('  </script></div>');
document.write('  </div>');
document.write('    <div class="navigation">');
document.write('      <div class="userBx">');
document.write('        <div class="imgBx">');
document.write('          <img src="https://bcm.teleporthq.app/playground_assets/image-300h.png" alt="user avatar" />');
document.write('        </div>');
document.write('        <p class="username">BCM</p>');
document.write('      </div>');
document.write('      <div class="menuToggle"></div>');
document.write('      <ul class="menu">');
document.write('        <li>');
document.write('          <a href="#"><ion-icon name="person-outline"></ion-icon>Profile</a>');
document.write('        </li>');
document.write('        <li>');
document.write('          <a href="#"');
document.write('            ><ion-icon name="chatbubble-outline"></ion-icon>Messages</a');
document.write('          >');
document.write('        </li>');
document.write('        <li>');
document.write('          <a href="#"');
document.write('            ><ion-icon name="notifications-outline"></ion-icon>Notification</a');
document.write('          >');
document.write('        </li>');
document.write('        <li>');
document.write('          <a href="#"><ion-icon name="settings-outline"></ion-icon>Settings</a>');
document.write('        </li>');
document.write('        <li>');
document.write('          <a href="#"><ion-icon name="log-out-outline"></ion-icon>Logout</a>');
document.write('        </li>');
document.write('      </ul>');
document.write('    </div>');
document.write('  ');
document.write('    <script');
document.write('      type="module"');
document.write('      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"');
document.write('    ></script>');
document.write('    <script');
document.write('      nomodule');
document.write('      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"');
document.write('    ></script>');
document.write('  ');
document.write('    <script>');
document.write('      let menuToggle = document.querySelector(".menuToggle");');
document.write('      let navigation = document.querySelector(".navigation");');
document.write('      menuToggle.onclick = function () {');
document.write('        navigation.classList.toggle("active");');
document.write('      };');
document.write('    </script>');
document.write('    <script>');
document.write('  try {');
document.write('  fetch(new Request("https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js", { method: \'HEAD\', mode: \'no-cors\' })).then(function(response) {');
document.write('    return true;');
document.write('  }).catch(function(e) {');
document.write('    var carbonScript = document.createElement("script");');
document.write('    carbonScript.src = "//cdn.carbonads.com/carbon.js?serve=CE7DC2JW&placement=wwwcssscriptcom";');
document.write('    carbonScript.id = "_carbonads_js";');
document.write('    document.getElementById("carbon-block").appendChild(carbonScript);');
document.write('  });');
document.write('  } catch (error) {');
document.write('  console.log(error);');
document.write('  }');
document.write('  </script>');
document.write('  <script async src="https://www.googletagmanager.com/gtag/js?id=G-LLWL5N9CSM"></script>');
document.write('  <script>');
document.write('  window.dataLayer = window.dataLayer || [];');
document.write('  function gtag(){dataLayer.push(arguments);}');
document.write('  gtag(\'js\', new Date());');
document.write('  gtag(\'config\', \'G-LLWL5N9CSM\');');
document.write('  </script>');
document.write('  </body>');
document.write('  </html>');
document.write('    </script>');
document.write('    <title>Page Title</title>');
document.write('  </head>');
